# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A)
print(A.dtype.name)
print(A.shape)
print(A.ndim)
print(A.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
int32
(3, 5)
2
15


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
print(B*C)
print(B-C)
print(B@C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.exp(B))
print(B.min())
print(B.min(axis=1))
print(B.min(axis=0))
print(np.argmin(B))
print(B.argmin(axis=1))
print(B.sum())
print(B.mean())
print(np.median(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
5.0
5.0


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [11]:
# When using A[1] it means that you slice the row on place 1 so the second row. Since you only gives it 1 value it "fills" out the other dimensions
# itself or rather consider them complete slices

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [12]:

A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [15]:
for i in A:
    for j in i:
        (print(j))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [16]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [17]:
# a skapar en lista med 30 värden. B ändrar sen listans form till 2 st matriser med 3 rader. Man kan använda sig utan -1 i sista axesen så anpassar
# datorn (i brist på bättre ord) hur lång raden ska vara. Skulle vi sätta in en trea där istället skulle vi få felmeddelande men sätter vi in en
# femma så fungerar det.


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [18]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [19]:
v1 = np.array([1, 2, 3])
print(v1 + 1)
print(v1)

[2 3 4]
[1 2 3]


In [20]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [21]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [4]:
def add_mult_matrices(a,b,c):
    if isinstance(a, np.ndarray) and isinstance(b, np.ndarray):
        if c == "add":
            if np.shape(a) == np.shape(b):
                sum = a + b
                return sum
            else:
                raise Exception("Wrong dimensions")   
        elif c == "mult":
            if a.shape[1] == b.shape[0]:
                sum = a @ b
                return sum
            else: 
                raise Exception("Wrong dimensions")
                 
        else:
            raise Exception("Make sure type is numpy.ndarray and you write add or mult")
            
    else:
        raise Exception("Make sure type is numpy.ndarray and you write add or mult")

In [14]:
# Uppgift 
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])

print(add_mult_matrices(B,-2*A,"add"))
print(add_mult_matrices(C,D,"mult"))
print(add_mult_matrices(C,B,"mult"))
print(add_mult_matrices(A,C,"mult"))
print(add_mult_matrices(3*C,-E,"add"))

[[ 0 -4  3]
 [ 0 -2 -4]]
[[11 10]
 [10 11]]
[[  8 -10  -3]
 [ 10  -8   0]]


Exception: Wrong dimensions

**Chap2. Question 2**

In [24]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = add_mult_matrices(A, B, "mult")
AC = add_mult_matrices(A, C, "mult")

print(AB)
print()
print(AC)
print("Med vår print kan vi se att AB = AC") 

print(B)
print()
print(C)
print("Med vår print kan vi se att B ej är lika med C") 


print((AB == AC).all())
print("Då vi får värdet True innebär det att dom är lika")

print((B == C).all())
print("Då vi får värdet False innebär det att dom ej är lika")

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]
Med vår print kan vi se att AB = AC
[[2 1]
 [1 3]]

[[4 3]
 [0 2]]
Med vår print kan vi se att B ej är lika med C
True
Då vi får värdet True innebär det att dom är lika
False
Då vi får värdet False innebär det att dom ej är lika


**Chap2. Question 3**

In [25]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print(add_mult_matrices(A, D, "mult"))
print()
print(add_mult_matrices(D, A, "mult"))

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [13]:
aa = np.array([[1, -1,], [-1, 1]])
bb = np.array([[-1, 1], [1, -1]])

a = np.array([[-2, 2], [2, -2]])
b = np.array([[2, -2], [-2, 2]])
c = np.array([[-2, 2], [-2, 2]])
d = np.array([[-2, -2], [2, 2]])

ab = add_mult_matrices(aa,bb,"mult")
print("is AB = a", (ab == a).all())
print("is AB = b", (ab == b).all())
print("is AB = c", (ab == c).all())
print("is AB = d", (ab == d).all())

is AB = a True
is AB = b False
is AB = c False
is AB = d False


**Chap 6. Question 1**

In [15]:
a = np.array([[5, 6], [4, 5]])
b = np.array([[6, 4], [3, 3]])

inva = np.linalg.inv(a)
invb = np.linalg.inv(b)
print("Matrix a")
print(a)    
print()
print("Inversion of a")
print(inva)
print()
print("Matrix b")
print(b)
print()
print("Inversion of b")
print(invb)

Matrix a
[[5 6]
 [4 5]]

Inversion of a
[[ 5. -6.]
 [-4.  5.]]

Matrix b
[[6 4]
 [3 3]]

Inversion of b
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [18]:
bas = np.array([[2, 2,], [1, 2]])
invb = np.linalg.inv(bas)
a = np.array([[2, -2], [-1, 2]])
b = np.array([[-2, 2], [1, -2]])
c = np.array([[2, 2], [-1, -2]])
d = np.array([[-2, -2], [1, 2]])

aa = a * 0.5
bb = b * 0.5
cc = c * 0.5
dd = d * 0.5
print("Is a inverse of bas")
print(np.allclose(invb, aa))
print()
print("Is b inverse of bas")
print(np.allclose(invb, bb))
print()
print("Is c inverse of bas")
print(np.allclose(invb, cc))
print()
print("Is d inverse of bas")
print(np.allclose(invb, dd))
print()

Is a inverse of bas
True

Is b inverse of bas
False

Is c inverse of bas
False

Is d inverse of bas
False



**Chap10. Question 1 a)**

In [9]:
a = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])
x = np.linalg.solve(a, b)

print("Vad är x?")
print(x)
print()
print("Kolla om det stämmer")
print(np.allclose(np.dot(a, x), b))

Vad är x?
[ 3.  4. -6.]

Kolla om det stämmer
True


**Chap10. Question 1 b)**

In [ ]:
a = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])
x = np.linalg.solve(a, b)

print("Vad är x?")
print(x)
print()
print("Kolla om det stämmer")
print(np.allclose(np.dot(a, x), b))

**Chap 12. Question 1**

In [12]:
a = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
inva = np.linalg.inv(a)
print(inva)

print("Is inva inverse of a")
print(np.allclose(np.dot(a, inva),np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
Is inva inverse of a
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)